package metier;
// Generated Mar 27, 2020 12:45:14 PM by Hibernate Tools 4.3.1



/**
 * Affecter generated by hbm2java
 */
public class Affecter  implements java.io.Serializable {


     private AffecterId id;
     private Creneau creneau;
     private Personnel personnel;
     private byte[] signatureEnseignant;
     private String etatPresence;
     private String etatValide;

    public Affecter() {
    }

	
    public Affecter(AffecterId id, Creneau creneau, Personnel personnel) {
        this.id = id;
        this.creneau = creneau;
        this.personnel = personnel;
    }
    public Affecter(AffecterId id, Creneau creneau, Personnel personnel, byte[] signatureEnseignant, String etatPresence, String etatValide) {
       this.id = id;
       this.creneau = creneau;
       this.personnel = personnel;
       this.signatureEnseignant = signatureEnseignant;
       this.etatPresence = etatPresence;
       this.etatValide = etatValide;
    }
   
    public AffecterId getId() {
        return this.id;
    }
    
    public void setId(AffecterId id) {
        this.id = id;
    }
    public Creneau getCreneau() {
        return this.creneau;
    }
    
    public void setCreneau(Creneau creneau) {
        this.creneau = creneau;
    }
    public Personnel getPersonnel() {
        return this.personnel;
    }
    
    public void setPersonnel(Personnel personnel) {
        this.personnel = personnel;
    }
    public byte[] getSignatureEnseignant() {
        return this.signatureEnseignant;
    }
    
    public void setSignatureEnseignant(byte[] signatureEnseignant) {
        this.signatureEnseignant = signatureEnseignant;
    }
    public String getEtatPresence() {
        return this.etatPresence;
    }
    
    public void setEtatPresence(String etatPresence) {
        this.etatPresence = etatPresence;
    }
    public String getEtatValide() {
        return this.etatValide;
    }
    
    public void setEtatValide(String etatValide) {
        this.etatValide = etatValide;
    }




}


