package metier;
// Generated Mar 27, 2020 12:45:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Groupe generated by hbm2java
 */
public class Groupe  implements java.io.Serializable {


     private String idGroupe;
     private String typeGroupe;

     private String typeFormation;
     private String dateDeb;
     private String dateFin;
     private String nomGroupe;
     private Set periodes = new HashSet(0);

     private Set creneaus = new HashSet(0);
     private Set personnels = new HashSet(0);

    public Groupe() {
    }

	

    public Groupe(String idGroupe, String typeGroupe, String typeFormation, String dateDeb, String dateFin, String nomGroupe) {

        this.idGroupe = idGroupe;
        this.typeGroupe = typeGroupe;
        this.typeFormation = typeFormation;
        this.dateDeb = dateDeb;
        this.dateFin = dateFin;
        this.nomGroupe = nomGroupe;
    }

    public Groupe(String idGroupe, String typeGroupe, String typeFormation, String dateDeb, String dateFin, String nomGroupe, Set periodes, Set creneaus, Set personnels) {

       this.idGroupe = idGroupe;
       this.typeGroupe = typeGroupe;
       this.typeFormation = typeFormation;
       this.dateDeb = dateDeb;
       this.dateFin = dateFin;
       this.nomGroupe = nomGroupe;
       this.periodes = periodes;
       this.creneaus = creneaus;
       this.personnels = personnels;
    }
   
    public String getIdGroupe() {
        return this.idGroupe;
    }
    
    public void setIdGroupe(String idGroupe) {
        this.idGroupe = idGroupe;
    }
    public String getTypeGroupe() {
        return this.typeGroupe;
    }
    
    public void setTypeGroupe(String typeGroupe) {
        this.typeGroupe = typeGroupe;
    }
    public String getTypeFormation() {
        return this.typeFormation;
    }
    
    public void setTypeFormation(String typeFormation) {
        this.typeFormation = typeFormation;
    }
    public String getDateDeb() {
        return this.dateDeb;
    }
    
    public void setDateDeb(String dateDeb) {
        this.dateDeb = dateDeb;
    }
    public String getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(String dateFin) {
        this.dateFin = dateFin;
    }
    public String getNomGroupe() {
        return this.nomGroupe;
    }
    
    public void setNomGroupe(String nomGroupe) {
        this.nomGroupe = nomGroupe;
    }
    public Set getPeriodes() {
        return this.periodes;
    }
    
    public void setPeriodes(Set periodes) {
        this.periodes = periodes;
    }
    public Set getCreneaus() {
        return this.creneaus;
    }
    
    public void setCreneaus(Set creneaus) {
        this.creneaus = creneaus;
    }
    public Set getPersonnels() {
        return this.personnels;
    }
    
    public void setPersonnels(Set personnels) {
        this.personnels = personnels;
    }




}


