package metier;
// Generated Mar 27, 2020 12:45:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Justifier generated by hbm2java
 */
public class Justifier  implements java.io.Serializable {


     private JustifierId id;
     private Creneau creneau;
     private Personnel personnel;
     private Date dateDeb;
     private Date dateFin;
     private int heureDeb;
     private int heureFin;

    public Justifier() {
    }

    public Justifier(JustifierId id, Creneau creneau, Personnel personnel, Date dateDeb, Date dateFin, int heureDeb, int heureFin) {
       this.id = id;
       this.creneau = creneau;
       this.personnel = personnel;
       this.dateDeb = dateDeb;
       this.dateFin = dateFin;
       this.heureDeb = heureDeb;
       this.heureFin = heureFin;
    }
   
    public JustifierId getId() {
        return this.id;
    }
    
    public void setId(JustifierId id) {
        this.id = id;
    }
    public Creneau getCreneau() {
        return this.creneau;
    }
    
    public void setCreneau(Creneau creneau) {
        this.creneau = creneau;
    }
    public Personnel getPersonnel() {
        return this.personnel;
    }
    
    public void setPersonnel(Personnel personnel) {
        this.personnel = personnel;
    }
    public Date getDateDeb() {
        return this.dateDeb;
    }
    
    public void setDateDeb(Date dateDeb) {
        this.dateDeb = dateDeb;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }
    public int getHeureDeb() {
        return this.heureDeb;
    }
    
    public void setHeureDeb(int heureDeb) {
        this.heureDeb = heureDeb;
    }
    public int getHeureFin() {
        return this.heureFin;
    }
    
    public void setHeureFin(int heureFin) {
        this.heureFin = heureFin;
    }




}


