package metier;
// Generated Mar 27, 2020 12:45:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Matiere generated by hbm2java
 */
public class Matiere  implements java.io.Serializable {


     private String libelleMatiere;
     private Formation formation;
     private Ue ue;
     private String initiale;
     private Set personnels = new HashSet(0);
     private Set creneaus = new HashSet(0);

    public Matiere() {
    }

	
    public Matiere(String libelleMatiere, Formation formation, Ue ue, String initiale) {
        this.libelleMatiere = libelleMatiere;
        this.formation = formation;
        this.ue = ue;
        this.initiale = initiale;
    }
    public Matiere(String libelleMatiere, Formation formation, Ue ue, String initiale, Set personnels, Set creneaus) {
       this.libelleMatiere = libelleMatiere;
       this.formation = formation;
       this.ue = ue;
       this.initiale = initiale;
       this.personnels = personnels;
       this.creneaus = creneaus;
    }
   
    public String getLibelleMatiere() {
        return this.libelleMatiere;
    }
    
    public void setLibelleMatiere(String libelleMatiere) {
        this.libelleMatiere = libelleMatiere;
    }
    public Formation getFormation() {
        return this.formation;
    }
    
    public void setFormation(Formation formation) {
        this.formation = formation;
    }
    public Ue getUe() {
        return this.ue;
    }
    
    public void setUe(Ue ue) {
        this.ue = ue;
    }
    public String getInitiale() {
        return this.initiale;
    }
    
    public void setInitiale(String initiale) {
        this.initiale = initiale;
    }
    public Set getPersonnels() {
        return this.personnels;
    }
    
    public void setPersonnels(Set personnels) {
        this.personnels = personnels;
    }
    public Set getCreneaus() {
        return this.creneaus;
    }
    
    public void setCreneaus(Set creneaus) {
        this.creneaus = creneaus;
    }




}


