package metier;
// Generated Mar 27, 2020 12:45:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Periode generated by hbm2java
 */
public class Periode  implements java.io.Serializable {


     private Integer noPeriode;
     private String dateDeb;
     private String dateFin;
     private String typePeriode;
     private Set groupes = new HashSet(0);

    public Periode() {
    }

	
    public Periode(String dateDeb, String dateFin, String typePeriode) {
        this.dateDeb = dateDeb;
        this.dateFin = dateFin;
        this.typePeriode = typePeriode;
    }
    public Periode(String dateDeb, String dateFin, String typePeriode, Set groupes) {
       this.dateDeb = dateDeb;
       this.dateFin = dateFin;
       this.typePeriode = typePeriode;
       this.groupes = groupes;
    }
   
    public Integer getNoPeriode() {
        return this.noPeriode;
    }
    
    public void setNoPeriode(Integer noPeriode) {
        this.noPeriode = noPeriode;
    }
    public String getDateDeb() {
        return this.dateDeb;
    }
    
    public void setDateDeb(String dateDeb) {
        this.dateDeb = dateDeb;
    }
    public String getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(String dateFin) {
        this.dateFin = dateFin;
    }
    public String getTypePeriode() {
        return this.typePeriode;
    }
    
    public void setTypePeriode(String typePeriode) {
        this.typePeriode = typePeriode;
    }
    public Set getGroupes() {
        return this.groupes;
    }
    
    public void setGroupes(Set groupes) {
        this.groupes = groupes;
    }




}


